### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by essamamdani** [vuegg/vuegg#16]
Please answer this question. I have been working on the task which is for the page/skin builder. I love Vue that's reason I started work on vuegg, there is 80% features has been developed by you for my product requirement. Also I have added many features according to product requirement, It's fun and easy to work on it. But since last week I have been got stuck to add hover feature on Main Container so that question is how can I implement the effect of hover and workable display on preview page?
![alt text](https://dha4w82d62smt.cloudfront.net/items/2c3n333Y1r0r2v1e0E01/Screen%20Recording%202018-04-26%20at%2005.06%20PM.gif?X-CloudApp-Visitor-Id=493c445e48ce9f82e3741bc378216dd7&v=d8852b86 "Hover Screenshot")

**Comment by essamamdani** [comment]
Hi,

To make my question simpler, I need to understand how I can impliment "Hover State" to an element. For example, on the button element I wish to add a hover background option which I can easily add cloning the background color option, how would I make it render on stage similar to how it works for Material components.
![alt text](https://dha4w82d62smt.cloudfront.net/items/0f2f0e0D1w2D2s0w0v1Q/Screen%20Recording%202018-04-26%20at%2006.40%20PM.gif?X-CloudApp-Visitor-Id=493c445e48ce9f82e3741bc378216dd7&v=3971a457 "Hover Screenshot")

**Comment by alxpez** [comment]
Hi @essamamdani,

I'm happy to see that you like vuegg and find it useful for your own developments.

Just to point it out, this is not an issue, neither a feature request, but rather a functionality for a forked project you're working on, which I will be really happy to checkout one you have it ready 😄!

On the other hand, I accept PRs for vuegg, if you think you have a useful functionality/addition please, do not hesitate to open one and contribute to the open community. Otherwise, notice that this project is released under a [MIT license](https://github.com/vuegg/vuegg/blob/master/LICENSE), do appropriately.

About your issue, I think what you want could be solved by adding a css rule to the button, for example:

```css
.your-button{
  background-color: #fff
}

.your-button:hover {
  background-color: #eee
}
```

That's about as much input I can give you off the top of my head. Please ping me with your project when to release it or deploy it to production, I will be happy to see any new project forked from vuegg, keep in touch.

Cheers!

**Comment by essamamdani** [comment]
Glad to see your respond @alxpez. It's secret mission project, I will show you when I will release. 👍

**Comment by alxpez** [comment]
Cool man! Let me know when ready. Cheers
