### ISSUE TITLE
[Feat] Update README/docs with local setup gotchas

### ISSUE THREAD

**Issue by Shuunen** [vuegg/vuegg#17]
Hi,

In order to build vuegg I had to install `libcurl-dev`  (I choose `libcurl4-openssl-dev` because `libcurl-dev` is a virtual package) and also `libssl-dev`

I'm on Linux Mint 18.3 Sylvia and I got these issues : 
- https://github.com/nodegit/nodegit/issues/1134
- https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory

So IMHO these 2 packages should be mentioned as requirements in the readme  :smiley: 

VueGG is working great now :+1:

**Comment by alxpez** [comment]
Hi @Shuunen 

Thanks for taking the time to point this out, although this seems to be more of a problem with nodegit rather than vuegg.

I may add a link to #17 under the [local setup](https://github.com/vuegg/vuegg#run-vuegg-locally) section, with any other known dependencies issues that may be raised.

Please feel free to edit the README/documentation (and open PR) to include this is you have some time.
