### ISSUE TITLE
[Bug] Generated vue sources do not match with what is shown in the editor

### ISSUE THREAD

**Issue by rustemgareev** [vuegg/vuegg#28]
Currently, top app bar can be moved to the any Y point of the page. Ideally, it should stay on top of the page, whether it "fixed-to-top" or not.

**Comment by alxpez** [comment]
Thanks @rustemgareev,

You're right, in fact if:
1. You place the **TopAppBar anywhere** in the editor
2. **Generate** vuejs sources
3. Then **run** your generated vue project
4. The **TopAppBar is fixed** to the top of the page _(as it should)_

So I see your point, now my question is if this fits under a Feature or a Bug.

Definitely it makes sense to limit the location of the TopAppBar, which I'll be implementing (I take that as a feature), but the current behaviour is buggy, since the generated project should match what is seen on the editor.

Thanks for reporting!

**Comment by alxpez** [comment]
I'll be leaving this issue for the bug on the sources generation, since #30 contains a reference to the feature related to fixing certain elements
