### ISSUE TITLE
is this still active ?

### ISSUE THREAD

**Issue by mapsgeek** [vuegg/vuegg#39]
App is amazing idea, personally i would be more than happy just to see 2 features
1- ability to add other UI libraries, vutefy, ant-design, etc ...
2- support layout grid, flexbox and export to html,css

but first feature would be a great implementation
thanks :)

**Comment by alxpez** [comment]
Thanks!

At the moment this repository is only maintained by me alone, and I don't have a lot of free time lately (I wish open-source was my job, but at the time it's only my hobby), since I have a full time job mon-fri.

However, I have some features that I would like to include to the core, but they need refining... and also there're some bugs that need extra attention before hand.

To be honest, I would love an extra pair of hand to tackle some of these tasks, it would be great to have some help to make this weekend project into something usable to a user level. Share the word to charitable people with free time :)

There're already some feature/issues referring to your requests, tho!

Cheers
